modLoader="javafml"
loaderVersion="[34,)"
license="CC BY-NC-SA 4.0"

[[mods]]
modId="jade"
version="${file.jarVersion}"
displayName="Jade"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/jade"
description="HWYLA addons"

[[mods]]
modId="waila"
version="${file.jarVersion}"
displayName="Waila (Jade)"
authors="Snownee, TehNut, ProfMobius"
description="You are using Jade, a fork of Hwyla."
